name: Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@2.1.1
    - name: apt update
      run: sudo apt update
    - name: apt install
      run: sudo apt install libsdl2-dev libsdl2-image-dev libopusfile-dev libmpg123-dev libflac-dev libvorbis-dev libopus-dev libjansson-dev
    - name: make clean
      run: make clean
    - name: make
      run: make
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: bin/
